---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debezium.fullname" . }}-connect
  labels:
    {{- include "debezium.labels.connect" . | nindent 4 }}
spec:
  replicas: {{ .Values.debezium.connect.replicaCount }}
  selector:
    matchLabels:
      {{- include "debezium.selectorLabels.connect" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.debezium.connect.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "debezium.selectorLabels.connect" . | nindent 8 }}
    spec:
      {{- with .Values.debezium.connect.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-connect
          image: "{{ .Values.debezium.connect.image.repository }}:{{ .Values.debezium.connect.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.debezium.connect.image.pullPolicy }}
          ports:
            - name: {{ .Values.debezium.connect.service.name }}
              containerPort: {{ .Values.debezium.connect.service.port }}
              protocol: {{ .Values.debezium.connect.service.protocol }}
          resources:
            {{- toYaml .Values.debezium.connect.resources | nindent 12 }}
          {{- with .Values.debezium.connect.env }}
          env:
            {{- toYaml . | nindent 12}}
          {{- end}}
          volumeMounts:
            - name: config-volume
              mountPath: /kafka-connect
      {{- with .Values.debezium.connect.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.debezium.connect.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.debezium.connect.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-connect-config
